In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix

In [30]:
file_path = r"C:\Users\MinGi\Desktop\year3-sem1\인공지능개론\dataset\iris.csv"
df = pd.read_csv(file_path)

print(df.head())

x = df.drop('Name', axis=1)
y = df['Name']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0, stratify=y)

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

   SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa


In [33]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(x_train, y_train)
y_pred_dt = dt_model.predict(x_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_dt))

Decision Tree Accuracy: 0.9777777777777777
[[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]


In [39]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(random_state=0)
rf_model.fit(x_train, y_train)
y_pred_rf = rf_model.predict(x_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))

Random Forest Accuracy: 0.9777777777777777
[[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]


In [35]:
# Support Vector Machine
from sklearn.svm import SVC

svm_model = SVC(random_state=0)
svm_model.fit(x_train_scaled, y_train)
y_pred_svm = svm_model.predict(x_test_scaled)

print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print(confusion_matrix(y_test, y_pred_svm))

SVM Accuracy: 0.9777777777777777
[[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]


In [38]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(random_state=0)
lr_model.fit(x_train_scaled, y_train)
y_pred_lr = lr_model.predict(x_test_scaled)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(confusion_matrix(y_test, y_pred_lr))

Logistic Regression Accuracy: 0.9777777777777777
[[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]


# K-Nearest Neighbors (KNN)
- 지도학습과 비지도학습 모두에서 사용되는 거리 기반 알고리즘
- 데이터가 속할 클래스를 결정할 때, **가장 가까운 K개의 이웃을 참조하여 다수를 차지하는 클래스로 분류**한다.
- 교차 분석을 통해 최적의 k 값을 찾아 n_neibors 값으로 사용하면 정확도를 높일 수 있다.

In [31]:
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

# 최적의 k 값 찾기
k_range = range(1, 21) # 1부터 20까지 테스트
scores = []
for k in k_range:
    knn = KNeighborsClassifier(n_neighbors=k)
    cvs = cross_val_score(knn, x_train_scaled, y_train, cv=5, scoring='accuracy')
    scores.append(cvs.mean()) # 평균 정확도를 scores에 추가
optimal_k = k_range[np.argmax(scores)]
print("최적의 k:", optimal_k)

# 최적의 k로 knn 분류 수행
knn = KNeighborsClassifier(n_neighbors=optimal_k)
knn.fit(x_train_scaled, y_train)
y_pred_knn = knn.predict(x_test_scaled)

print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))
print(confusion_matrix(y_test, y_pred_knn))

최적의 k: 4
KNN Accuracy: 0.9555555555555556
[[15  0  0]
 [ 0 15  0]
 [ 0  2 13]]
