In [35]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [34]:
file_path = r"C:\Users\MinGi\Desktop\year3-sem1\인공지능개론\dataset\mobile.csv"
df = pd.read_csv(file_path)

print(df.head())
print(df.columns)

x = df.drop('price_range', axis=1)
y = df['price_range']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

   battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_

In [41]:
# 1. Decision Tree (DT)
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(x_train, y_train)

y_pred_dt = dt_model.predict(x_test)
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_dt))

Decision Tree Accuracy: 0.8166666666666667
[[133  17   0   0]
 [ 15 113  22   0]
 [  0  13 111  26]
 [  0   0  17 133]]


In [24]:
y_pred_dt_series = pd.Series(y_pred_dt, index=y_test.index, name="price_range")
print(y_test)
print(y_pred_dt_series)

570     3
414     3
1837    1
1510    1
1130    3
       ..
544     1
1303    3
1193    0
1818    0
67      3
Name: price_range, Length: 600, dtype: int64
570     3
414     3
1837    1
1510    2
1130    3
       ..
544     1
1303    2
1193    0
1818    0
67      3
Name: price_range, Length: 600, dtype: int64


In [9]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(x_train, y_train)

y_pred_rf = rf_model.predict(x_test)
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

Random Forest Accuracy: 0.8716666666666667
              precision    recall  f1-score   support

           0       0.96      0.95      0.96       150
           1       0.83      0.88      0.85       150
           2       0.82      0.73      0.77       150
           3       0.87      0.92      0.90       150

    accuracy                           0.87       600
   macro avg       0.87      0.87      0.87       600
weighted avg       0.87      0.87      0.87       600



In [8]:
# 3. Support Vector Machine (SVM)
from sklearn.svm import SVC

svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(x_train_scaled, y_train)

y_pred_svm = svm_model.predict(x_test_scaled)
print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

SVM Accuracy: 0.9583333333333334
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       150
           1       0.93      0.95      0.94       150
           2       0.95      0.94      0.95       150
           3       0.97      0.99      0.98       150

    accuracy                           0.96       600
   macro avg       0.96      0.96      0.96       600
weighted avg       0.96      0.96      0.96       600



In [10]:
# 4. Logistic Regression (LR)
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(max_iter=200, random_state=42)
lr_model.fit(x_train_scaled, y_train)

y_pred_lr = lr_model.predict(x_test_scaled)
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

Logistic Regression Accuracy: 0.96
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       150
           1       0.94      0.96      0.95       150
           2       0.95      0.93      0.94       150
           3       0.95      0.99      0.97       150

    accuracy                           0.96       600
   macro avg       0.96      0.96      0.96       600
weighted avg       0.96      0.96      0.96       600



In [ ]:
from sklearn.neighbors import KNeighborClassifier

# KNN 모델 정의 및 훈련 (k=5)
knn = KNeightborClassifier(n_neighbors=5)
knn.fit(x_train, y_train)

# 예측
y_pred_knn = knn.predict(x_test)
print("KNN Acurracy:", accuracy_score(y_pred_knn, y_test)
print(classification_report(y_test, y_pred_knn))

In [25]:
print("a")

a


In [40]:
#  2. Random Forest (RF)
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(random_state=0)
rf_model.fit(x_train, y_train)

y_pred_rf = rf_model.predict(x_test)
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))

Random Forest Accuracy: 0.88
[[141   9   0   0]
 [  6 126  18   0]
 [  0  19 121  10]
 [  0   0  10 140]]


In [43]:
# 3. Support Vector Machine (SVM)
from sklearn.svm import SVC

svm_model = SVC(random_state=0)
svm_model.fit(x_train_scaled, y_train)

y_pred_svm = svm_model.predict(x_test_scaled)
print("Support Vector Machine Accuracy:", accuracy_score(y_test, y_pred_svm))
print(confusion_matrix(y_test, y_pred_svm))

Support Vector Machine Accuracy: 0.8683333333333333
[[140  10   0   0]
 [  5 125  20   0]
 [  0  12 124  14]
 [  0   0  18 132]]


In [46]:
# 4. Logistic Regression (LR)
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(random_state=0)
lr_model.fit(x_train_scaled, y_train)

y_pred_lr = lr_model.predict(x_test_scaled)
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(confusion_matrix(y_test, y_pred_lr))

Logistic Regression Accuracy: 0.96
[[145   5   0   0]
 [  1 144   5   0]
 [  0   4 139   7]
 [  0   0   2 148]]
