### 라이브러리 임포트

In [2]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

### 전처리

In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
y_train, y_test = to_categorical(y_train, 10), to_categorical(y_test, 10) 

 ### 모델 정의 및 컴파일

In [4]:
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

### 모델 학습 및 평가

In [5]:
model.fit(x_train, y_train, epochs=5, batch_size=32)
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"테스트 손실: {test_loss}")
print(f"테스트 정확도: {test_acc}")

Epoch 1/5


1875/1875 [==============================] - 14s 6ms/step - loss: 0.2384 - accuracy: 0.9302
Epoch 2/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1026 - accuracy: 0.9689
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0729 - accuracy: 0.9779
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0541 - accuracy: 0.9831
Epoch 5/5
313/313 [==============================] - 1s 3ms/step - loss: 0.0821 - accuracy: 0.9762
테스트 손실: 0.08206261694431305
테스트 정확도: 0.9761999845504761


In [6]:
pred = model.predict(x_test)
pred_labels = np.argmax(pred, axis=1)

y_labels = np.argmax(y_test, axis=1) # 원-핫 인코딩 -> 정수형 클래스 라벨
print(confusion_matrix(y_labels, pred_labels), "\n") # Confusion Matrix
print(classification_report(y_labels, pred_labels)) # 전체 지표

313/313 [==============================] - 1s 2ms/step
[[ 975    0    0    1    0    1    1    0    1    1]
 [   1 1126    0    2    0    1    2    0    3    0]
 [   4    2 1007    1    1    0    1   11    5    0]
 [   0    2    6  991    0    1    0    5    2    3]
 [   1    0    4    1  956    1    4    2    1   12]
 [   2    1    0   25    0  855    3    1    2    3]
 [   6    4    0    1    1    6  939    0    1    0]
 [   1    4    9    4    1    0    0 1002    1    6]
 [   4    1    4   18    2    2    2    3  935    3]
 [   2    3    0   13   10    0    0    3    2  976]] 

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.98      0.98      1032
           3       0.94      0.98      0.96      1010
           4       0.98      0.97      0.98       982
           5       0.99      0.96      0.97       892
           6       0.99      0.98