## 5주차 실습과제-2
ㅡ- car_evaluation 데이터셋 딥러닝 분류

In [65]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD, Adam

In [66]:
file_path = r"C:\Users\MinGi\Desktop\year3-sem1\인공지능개론\dataset\car_evaluation.csv"
df = pd.read_csv(file_path)

df.head()

vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [67]:
df.isnull().sum()

vhigh      0
vhigh.1    0
2          0
2.1        0
small      0
low        0
unacc      0
dtype: int64

In [71]:
for column in df.columns:
    if column != 'unacc':
        df[column] = LabelEncoder().fit_transform(df[column])
    print(df[column].value_counts())

vhigh
0    432
2    432
1    432
3    431
Name: count, dtype: int64
vhigh.1
0    432
2    432
1    432
3    431
Name: count, dtype: int64
2
1    432
2    432
3    432
0    431
Name: count, dtype: int64
2.1
1    576
2    576
0    575
Name: count, dtype: int64
small
1    576
0    576
2    575
Name: count, dtype: int64
low
2    576
0    576
1    575
Name: count, dtype: int64
unacc
unacc    1209
acc       384
good       69
vgood      65
Name: count, dtype: int64


In [72]:
x = df.drop('unacc', axis=1)
y = df['unacc']

scaler = StandardScaler()
x = scaler.fit_transform(x)

In [73]:
y = pd.get_dummies(y).values

x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.25,random_state=0)
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(1295, 6) (1295, 4)
(432, 6) (432, 4)


In [77]:
model = Sequential()

model.add(Dense(10,input_shape=(6,),activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(6,activation='relu'))
model.add(Dense(4,activation='softmax'))

model.compile(Adam(learning_rate=0.04),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━┓
┃                 ┃ Output      ┃  Param ┃
┃ Layer (type)    ┃ Shape       ┃      # ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━┩
│ dense_8 (Dense) │ (None, 10)  │     70 │
├─────────────────┼─────────────┼────────┤
│ dense_9 (Dense) │ (None, 8)   │     88 │
├─────────────────┼─────────────┼────────┤
│ dense_10        │ (None, 6)   │     54 │
│ (Dense)         │             │        │
├─────────────────┼─────────────┼────────┤
│ dense_11        │ (None, 4)   │     28 │
│ (Dense)         │             │        │
└─────────────────┴─────────────┴────────┘

 Total params: 240 (960.00 B)

 Trainable params: 240 (960.00 B)

 Non-trainable params: 0 (0.00 B)

In [78]:
model_history=model.fit(x=x_train, y=y_train, epochs=6, batch_size=32,validation_split=0.1)
y_pred = model.predict(x_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/6
37/37 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.6240 - loss: 0.9202 - val_accuracy: 0.7154 - val_loss: 0.6280
Epoch 2/6
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7399 - loss: 0.5650 - val_accuracy: 0.8077 - val_loss: 0.4739
Epoch 3/6
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8415 - loss: 0.4255 - val_accuracy: 0.8308 - val_loss: 0.3808
Epoch 4/6
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8505 - loss: 0.3437 - val_accuracy: 0.7846 - val_loss: 0.3750
Epoch 5/6
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3314 - val_accuracy: 0.8000 - val_loss: 0.4276
Epoch 6/6
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8589 - loss: 0.3048 - val_accuracy: 0.8769 - val_loss: 0.2687
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step


In [79]:
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.66      0.93      0.77        96
           1       0.83      0.28      0.42        18
           2       0.98      0.96      0.97       298
           3       0.00      0.00      0.00        20

    accuracy                           0.88       432
   macro avg       0.62      0.54      0.54       432
weighted avg       0.86      0.88      0.86       432

[[ 89   1   6   0]
 [ 13   5   0   0]
 [ 12   0 286   0]
 [ 20   0   0   0]]


C:\Users\MinGi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\MinGi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\MinGi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo