# 자료구조 기초



---



# 1.자료구조의 이해

## 다양한 자료구조

### @파이썬 자료구조

- 기본 자료구조(Built-in Data Structures)

|자료구조|특징|주요 메서드|시간 복잡도|
|---|--- |--- |--- |
|List|가변 길이, 순서 유지, 인덱싱 가능 |append(), insert(), remove(), pop(), sort(), reverse() |검색: O(1), 삽입/삭제: O(N) (중간 삽입/삭제 시), 끝 추가 O(1) |
|Tuple |불변, 순서 유지, 인덱싱 가능 |count(), index() |검색: O(1), 수정 불가 |
|Dictionary|키-값 쌍 저장, 해시 기반, 순서 유지 (3.7+) |get(), keys(), values(), items(), pop(), update() |검색/삽입/삭제: 평균 O(1), 최악 O(N) |
|Set |중복 불가, 순서 없음 |add(), remove(), union(), intersection(), difference() |삽입/삭제/검색: 평균 O(1), 최악 O(N) |

- 추상 자료형(ADT, Abstract Data Type)

|ADT|파이썬 구현|특징|주요 연산|시간 복잡도|
|---|--- |--- |--- |--- |
|Stack |list, collections.deque |후입선출(LIFO) |push(), pop(), peek() |O(1) |
|Queue |collections.deque, queue.Queue |선입선출(FIFO) |enqueue(), dequeue() |O(1) |
|Priority Queue |queue.PriorityQueue, heapq |우선순위 기반 |push(), pop() |O(log N) |
|Deque |collections.deque |양방향 삽입/삭제 가능 |append(), appendleft(), pop(), popleft() |O(1) |
|Linked List |class로 직접 구현 |연결된 노드 구조 |insert(), delete(), search() |O(N) |
|Graph |dict + list, dict + set |노드와 엣지로 구성 |add_node(), add_edge(), remove_edge(), search() |O(V+E) |
|Tree |class로 직접 구현 |계층 구조 |insert(), delete(), traverse() |O(log N) (이진 트리) |




---



# 2.기초 자료구조

## 배열(Array)
- 동일한 타입의 요소들이 연속적인 메모리 공간에 저장된 자료구조
- 인덱스(Index)를 사용하여 요소에 빠르게 접근
- 데이터 검색과 순차적인 데이터 처리를 위해 최적화된 자료구조

### @배열의 특징

|특징|설명|
|----|----|
|고정된 크기 (Static Size)  |배열은 일반적으로 선언 시 크기가 고정됨 (동적 배열은 예외)  |
|연속적인 메모리 할당 (Contiguous Memory Allocation)  |모든 요소가 연속된 메모리 주소에 저장됨 → 빠른 접근 가능 (𝑂(1))  |
|인덱스를 이용한 빠른 접근 (Index-Based Access)  |특정 요소에 𝑂(1) 의 시간 복잡도로 접근 가능.  |
|데이터 추가/삭제가 비효율적  |배열 크기가 고정되어 있으며, 요소 삽입/삭제 시 비효율적(𝑂(𝑛))  |

        

- 고정된 크기 (Static Size)

In [1]:
// 고정된 크기 (Static Size) : C 언어
#include <stdio.h>
#define SIZE 5  // 배열 크기 정의

int main() {
    int fixed_array[SIZE] = {1, 2, 3, 4, 5}; // 크기가 5인 정수형 배열 선언

    // 배열 요소 출력
    printf("배열 요소: ");
    for (int i = 0; i < SIZE; i++) {
        printf("%d ", fixed_array[i]);
    }

    // 크기를 초과한 요소 추가 시 오류 (컴파일러에서 허용하지 않음)
    fixed_array[5] = 6;

    return 0;
}

SyntaxError: invalid syntax (3299071130.py, line 1)

In [2]:
# 고정된 크기 (Static Size)
'''
파이썬의 기본 list는 동적 배열(dynamic array)이어서
고정된 크기처럼 사용하기 위해 임의의 class를 만들어 테스트
'''
import array

class FixedSizeArray:
    def __init__(self, size):
        self.array = array.array('i', [0] * size)  # 고정 크기 배열 초기화
        self.size = size
        self.count = 0  # 현재 저장된 요소 개수

    def insert(self, value):
        if self.count < self.size:
            self.array[self.count] = value
            self.count += 1
        else:
            raise ValueError("배열 크기를 초과하여 삽입할 수 없습니다!")

    def display(self):
        print(self.array[:self.count])  # 실제 저장된 요소만 출력

# 고정 크기 배열 생성 (크기 5)
fixed_array = FixedSizeArray(5)
fixed_array.insert(10)
fixed_array.insert(20)
fixed_array.insert(30)
fixed_array.insert(40)
fixed_array.insert(50)

fixed_array.display()  # 출력: array('i', [10, 20, 30, 40, 50])

# 크기 초과 시 오류 발생
try:
    fixed_array.insert(60)  # 오류 발생
except Exception as e:
    print("오류 발생:", e)


array('i', [10, 20, 30, 40, 50])
오류 발생: 배열 크기를 초과하여 삽입할 수 없습니다!


- 연속적인 메모리 할당 (Contiguous Memory Allocation)

In [3]:
import array

arr = array.array('i', [10, 20, 30, 40, 50])

# 배열의 메모리 주소 확인
print(f"배열 시작 주소: {id(arr)}")
print(f"첫 번째 요소의 주소: {id(arr[0])}")
print(f"두 번째 요소의 주소: {id(arr[1])}")  # 연속적인 메모리 주소 확인


배열 시작 주소: 1768411462080
첫 번째 요소의 주소: 140707194411736
두 번째 요소의 주소: 140707194412056


- 인덱스를 이용한 빠른 접근 (Index-Based Access)

In [4]:
arr = [100, 200, 300, 400, 500]

# 인덱스를 이용한 O(1) 접근
print(arr[0])  # 출력: 100
print(arr[2])  # 출력: 300
print(arr[4])  # 출력: 500

100
300
500


- 데이터 추가/삭제가 비효율적 : 요소들이 이동해야 한다.

In [5]:
arr = [10, 20, 30, 40, 50]

# 인덱스 2 위치에 25 삽입 (30 앞에 추가됨)
arr.insert(2, 25)
print(arr)  # 출력: [10, 20, 25, 30, 40, 50]

arr.pop(2)
print(arr)  # 출력: [10, 20, 30, 40, 50]

[10, 20, 25, 30, 40, 50]
[10, 20, 30, 40, 50]


### @배열의 주요 연산 및 시간 복잡도

|연산|설명|시간 복잡도|
|----|----|----|
|접근 (Access)|특정 인덱스의 요소를 가져오기  | O(1) |
|검색 (Search)  |특정 요소 찾기 (선형 검색)  | O(n) |
|삽입 (Insert)  |특정 위치에 요소 삽입  |O(n)  |
|삭제 (Delete)  |특정 위치 요소 삭제  |O(n)  |

In [ ]:
# 접근(Access) : O(1)
arr = [10, 20, 30, 40, 50]

# O(1) - 특정 인덱스의 요소 접근
print("인덱스 2의 값:", arr[2])  # 출력: 30
print("인덱스 4의 값:", arr[4])  # 출력: 50

In [6]:
# 검색(Search) : O(n)
def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i  # 인덱스 반환
    return -1  # 요소가 없을 경우

arr = [10, 20, 30, 40, 50]
print("30의 위치:", linear_search(arr, 30))  # 출력: 2
print("100의 위치:", linear_search(arr, 100))  # 출력: -1 (없음)


30의 위치: 2
100의 위치: -1


In [1]:
# 삽입(Insert) : O(n)
arr = [10, 20, 30, 40, 50]

# O(1) - 배열의 끝에 요소 추가
arr.append(60)
print("배열 끝에 60 추가:", arr)  # 출력: [10, 20, 30, 40, 50, 60]

# O(n) - 배열 중간에 요소 삽입 (인덱스 2에 25 삽입)
arr.insert(2, 25)
print("배열 중간에 25 삽입:", arr)  # 출력: [10, 20, 25, 30, 40, 50, 60]


배열 끝에 60 추가: [10, 20, 30, 40, 50, 60]
배열 중간에 25 삽입: [10, 20, 25, 30, 40, 50, 60]


In [ ]:
# 삭제(Delete) : O(n)
arr = [10, 20, 30, 40, 50]

# O(1) - 배열의 끝 요소 삭제
arr.pop()
print("배열 끝 요소 삭제:", arr)  # 출력: [10, 20, 30, 40]

# O(n) - 배열 중간 요소 삭제 (인덱스 2 요소 삭제)
arr.pop(2)
print("배열 중간 요소 삭제:", arr)  # 출력: [10, 20, 40]


### @배열의 종류

- **1차원  배열(One-Dimensional Array)** :
가장 기본적인 형태의 배열

In [ ]:
arr = [10, 20, 30, 40, 50]
print(arr[2])  # 출력: 30

- **2차원  배열 (Two-Dimensional Array)** :  행(row)과 열(column)로 구성된 배열 (행렬)


In [7]:
# 리스트 자료형으로 만든 2차원 배열 형태
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

print(matrix[1][2])  # 출력: 6

6


In [2]:
# numpy 라이브러리 array 자료형으로 만든 2차원 배열 형태
import numpy as np

# 2D 배열 (NumPy 사용)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("NumPy 2D 배열:")
print(matrix)

# 특정 요소 접근 (행: 1, 열: 2 -> 값: 6)
print("matrix[1, 2]:", matrix[1, 2])  # 출력: 6


NumPy 2D 배열:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix[1, 2]: 6


- **다차원  배열 (Multi-Dimensional Array)** :  3차원 이상의 배열, 이미지 처리, 그래픽 연산, 머신러닝에서 활용  


In [3]:
# 3D 배열 (2x2x2 배열)
array_3d = [
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
]

# 특정 요소 접근 (첫 번째 블록, 두 번째 행, 두 번째 열 -> 값: 4)
print("array_3d[0][1][1]:", array_3d[0][1][1])  # 출력: 4

# 3D 배열 출력
print("3차원 배열:")
for matrix in array_3d:
    for row in matrix:
        print(row)


array_3d[0][1][1]: 4
3차원 배열:
[1, 2]
[3, 4]
[5, 6]
[7, 8]


In [ ]:
# 컬러 이미지 파일은 3차원 배열구조로 되어 있는 것 확인하기
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# 이미지 파일 읽기
image = Image.open("cat.jpg")

# NumPy 배열로 변환
image_array = np.array(image)

# 다차원 배열 확인
print("이미지 배열 형태:", image_array.shape)  # (높이, 너비, 채널)
print("배열 차원 수:", image_array.ndim)  # 3이면 컬러 이미지

# Matplotlib을 이용하여 이미지 출력
plt.imshow(image)
plt.axis("off")  # 축 제거
plt.show()


- **동적 배열 (Dynamic Array)** : 가장 크기가 가변적으로 조정됨(Python list, C++ vector) 요소 추가 시 자동으로 메모리 재할당 및 확장-

In [4]:
arr = [1, 2, 3, 4, 5]
print("초기 배열:", arr)

# 요소 추가 (동적 크기 증가)
arr.append(6)
print("요소 추가 후:", arr)

# 요소 삭제 (동적 크기 감소)
arr.pop()
print("요소 삭제 후:", arr)


초기 배열: [1, 2, 3, 4, 5]
요소 추가 후: [1, 2, 3, 4, 5, 6]
요소 삭제 후: [1, 2, 3, 4, 5]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("초기 배열:", arr)

# 요소 추가 (새 배열 생성)
arr = np.append(arr, 6)
print("요소 추가 후:", arr)

# 요소 삭제 (새 배열 생성)
arr = np.delete(arr, -1)  # 마지막 요소 삭제
print("요소 삭제 후:", arr)


초기 배열: [1 2 3 4 5]
요소 추가 후: [1 2 3 4 5 6]
요소 삭제 후: [1 2 3 4 5]


### [실습] 배열 구조 출력하기
임의의 정수 12개를 발생시켜 1차원, 2차원(3x4), 3차원(2x2x3) 배열 구조로 출력하기

In [8]:
import numpy as np

numbers = np.random.randint(1, 101, 12)
numbers = np.array(numbers)

# 1차원 배열
print("1차원 배열:\n", numbers)

# 2차원 배열 (3x4) 전환
arr_2d = numbers.reshape(3, 4)
print("\n2차원 배열 (3x4):\n", arr_2d)

# 3차원 배열 (2x2x3) 전환
arr_3d = numbers.reshape(2, 2, 3)
print("\n3차원 배열 (2x2x3):\n", arr_3d)

1차원 배열:
 [ 2 47 82 70 47 44 35 46 33 23 47 37]

2차원 배열 (3x4):
 [[ 2 47 82 70]
 [47 44 35 46]
 [33 23 47 37]]

3차원 배열 (2x2x3):
 [[[ 2 47 82]
  [70 47 44]]

 [[35 46 33]
  [23 47 37]]]




---



## 스택(Stack)

- 다른 통로들은 모두 막고 한쪽만을 열어둔 구조
- 후입선출(LIFO:Last-In First-Out)/선입후출(FILO)의 자료구조

### @스택의 연산
|연산|설명|
|---|---|
|push(e) |스택의 맨 위에 데이터(요소) 삽입 |
|pop() |스택의 맨 위에 있는 요소 제거 |
|peek/top() |스택의 맨 위에 있는 항목을 삭제하지 않고 반환,  데이터 참조  |
|isEmpty() |스택이 비어 있는지 확인, True/False 반환 |
|isFull() |스택이 가득 차 있는지 확인, True/False 반환 |
|size() |스택에 들어 있는 전체 요소의 수 반환 |


### @배열로 스택 구현하기

- 전역변수 지정하기

In [ ]:
capacity = 10            # 스택 용량: 10으로 지정
array = [None]*capacity  # 요소 배열: [None,..,None] 길이(capacity)
top = -1                 # 스택 상단의 인덱스 : 공백 상태(-1)로 초기화

- 스택 연산 - 공백 상태 : isEmpty()

In [ ]:
def isEmpty():
    if top == -1:
        return True
    else:
        return False

- 스택 연산 - 포화 상태 : isEmpty()

In [ ]:
def isFull():
    return top == capacity    # 비교 연산 결과를 바로 반환

- 스택 연산 - 추가 : push(e)

In [ ]:
def push(e):
    global top
    if not isFull():             # 포화 상태가 아닌 경우
        top += 1                 # top 증가()
        array[top] = e           # top 위치에 e 복사
    else:                        # 포화 상태 : overflow
        print('stack overflow!')
        exit()

- 스택 연산 - 삭제 : pop()

In [ ]:
def pop():
    global top
    if not isEmpty():            # 공백 상태가 아닌 경우
        top -= 1                 # top 감소
        return array[top+1]      # 이전(top+1) 위치의 요소 반환
    else:                        # 공백 상태 : underflow
        print('stack underflow!')
        exit()

- 스택 연산 - 상단 요소 참조 : peek()

In [ ]:
def peek():
    if not isEmpty():
        return array[top]
    else:
        print("Stack is empty!")
        exit()

- 스택 연산 - 현재 스택 요소 수(크기) 반환 : size()

In [ ]:
def size():
    return top+1     # 현재 요소의 수

### [실습] 스택 클래스 구현하기

In [ ]:
# 1. ArrayStack 이란 이름의 빈 스택 클래스 작성하기 (사이즈 제한 없는)
class ArrayStack:
    def __init__(self):
        """ 스택 초기화 """
        self.stack = []

In [4]:
# 2. ArrayStack에 push(), pop(), peek(), isEmpty(), size() 메서드 추가하기
class ArrayStack:
    def __init__(self):
        """ 스택 초기화 """
        self.stack = []

    def isEmpty(self):
        """ 스택이 비어있는지 확인 """
        return len(self.stack) == 0

    def push(self, item):
        """ 스택에 요소 추가 """
        self.stack.append(item)

    def pop(self):
        """ 스택에서 요소 제거 """
        if self.isEmpty():
            print("Stack underflow")
            return
        else:
            return self.stack.pop()

    def peek(self):
        """ 스택의 최상위 요소 반환 """
        if self.isEmpty():
            print("Stack overflow")
            return
        else:
            return self.stack[-1]

    def size(self):
        """ 스택의 크기 반환 """
        return len(self.stack)

In [6]:
# 3. 스택 연산 실행하기
# 스택 인스턴스 생성
stack = ArrayStack()

# 스택 연산
print(f'(a) {stack.stack}')
stack.push('A'); print(f"(b) {stack.stack}")
stack.push('B'); print(f"(c) {stack.stack}")
stack.push('C'); print(f"(d) {stack.stack}")
print(f"Stack size: {stack.size()}")
print(f"(e) {stack.pop()}")
print(f"(f) {stack.pop()}")
print(f"Stack peek: {stack.peek()}")
print(f"Stack isEmpty: {stack.isEmpty()}")

(a) []
(b) ['A']
(c) ['A', 'B']
(d) ['A', 'B', 'C']
Stack size: 3
(e) C
(f) B
Stack peek: A
Stack isEmpty: False


In [10]:
# 4. Stack에 사이즈 제한 있도록 isFull() 매서드 추가하기

class ArrayStack:
    def __init__(self, capacity):
        """ 스택 초기화 """
        self.stack = []
        self.capacity = capacity
        self.top = -1

    def isEmpty(self):
        """ 스택이 비어있는지 확인 """
        return len(self.stack) == 0

    def isFull(self):
        """ 스택이 차있는지 확인 """
        return len(self.stack) >= self.capacity

    def push(self, item):
        """ 스택에 요소 추가 """
        if self.isFull():
            return
        else:
            self.stack.append(item)

    def pop(self):
        """ 스택에서 요소 제거 """
        if self.isEmpty():
            print("Stack underflow")
            return
        else:
            return self.stack.pop()

    def peek(self):
        """ 스택의 최상위 요소 반환 """
        if self.isEmpty():
            print("Stack overflow")
            return
        else:
            return self.stack[-1]

    def size(self):
        """ 스택의 크기 반환 """
        return len(self.stack)

stack = ArrayStack(10)

# 스택 연산
print(f'(a) {stack.stack}')
stack.push('A'); print(f"(b) {stack.stack}")
stack.push('B'); print(f"(c) {stack.stack}")
stack.push('C'); print(f"(d) {stack.stack}")
print(f"Stack size: {stack.size()}")
print(f"(e) {stack.pop()}")
print(f"(f) {stack.pop()}")
print(f"Stack peek: {stack.peek()}")
print(f"Stack isEmpty: {stack.isEmpty()}")

(a) []
(b) ['A']
(c) ['A', 'B']
(d) ['A', 'B', 'C']
Stack size: 3
(e) C
(f) B
Stack peek: A
Stack isEmpty: False


### @스택의 응용 : 괄호 검사

**괄호 검사 알고리즘 조건**
- 조건1 :  왼쪽 괄호의 개수와 오른쪽 괄호의 개수가 같아야 한다.
- 조건2 :  같은 종류인 경우 왼쪽 괄호가 오른쪽보다 먼저 나와야 한다.
- 조건3 :  다른 종류의 괄호 쌍이 서로 교차하면 안 된다.

### [실습] 괄호 검사 알고리즘 구현하기

- 빈 스택을 준비합니다.
- 입력된 문자를 하나씩 읽어 왼쪽 괄호를 만나면 스택에 삽입합니다.
- 오른쪽 괄호를 만나면 가장 최근에 삽입된 괄호를 스택에서 꺼냅니다. 이때 스택이 비었다면 오
른쪽 괄호가 먼저 나온 상황이므로 조건 2에 위배됩니다.
- 꺼낸 괄호가 오른쪽 괄호와 짝이 맞지 않으면 조건 3에 위배됩니다.
- 입력 문자열을 끝까지 처리했는데 스택에 괄호가 남아 있으면 괄호의 개수가 같지 않으므로 조
건 1에 위배됩니다. 모든 문자를 처리하고 스택이 공백 상태이면 검사 성공입니다.

1.괄호 검사 알고리즘 구현하기

In [11]:
def checkBrackets(statement):
    stack = ArrayStack(100)  # 빈 스택을 준비합니다.
    lefts = ['(', '{', '[']
    rights = [')', '}', ']']

    for c in statement:
        if c in lefts:
            stack.push(c)
        elif c in rights:
            if stack.isEmpty():
                return False
            if stack[stack.peek()] == c:
                stack.pop()




    # 스택이 공백 상태면 검사 성공
    return stack.isEmpty()

IndentationError: expected an indented block after 'if' statement on line 10 (1417841994.py, line 11)

In [ ]:
str1 = "{ A[(i+1)]=0; }"
str2 = "if ((x<0) && (y<3)"
str3 = "while (n<8)) {n++;}"
str4 = "arr[(i+1])=0;"

print(str1, " ---> \t", checkBrackets(str1))
print(str2, " ---> ", checkBrackets(str2))
print(str3, " --->", checkBrackets(str3))
print(str4, " ---> \t", checkBrackets(str4))

### @파이썬에서 스택 사용하기
- 예제: 문자열 역순으로 출력하기 사용

#### 방법 1) Stack 클래스 직접 구현해서 사용하기

In [ ]:
stack = ArrayStack(100) # 스택 생성

# 1.키보드로 문자열 입력 받기
msg = input('문자열 입력: ')
print('-' * 30)

# 2.문자열 스택에 추가하기
for c in msg:
    stack.push(c)

# 3.스택에서 문자열 꺼내서 출력하기
print('문자열 거꾸로 출력: ', end='')
while not stack.isEmpty():
    print(stack.pop(), end='')

#### 방법 2) 파이썬 리스트 함수 사용해서 스택으로 사용하기

In [ ]:
s = list()                      # 리스트를 객체를 생성해 스택으로 사용

msg = input("문자열 입력: ")
for c in msg :
    s.append(c)                 # c를 스택에 삽입

print("문자열 출력: ", end='')
while len(s) > 0:               # 스택이 공백상태가 아니라면
    print(s.pop(), end='')      # 하나의 요소를 꺼내서 출력
print()

#### 방법 3) 파이썬의 queue 모듈 LifoQueue 사용하기

In [ ]:
import queue                     # 파이썬의 큐 모듈 포함
s = queue.LifoQueue(maxsize=100) # 스택 객체 생성(용량=100)

msg = input("문자열 입력: ")
for c in msg :
    s.put(c)                     # c를 스택에 삽입

print("문자열 출력: ", end='')
while not s.empty():             # 스택이 공백상태가 아니라면
    print(s.get(), end='')       # 하나의 요소를 꺼내서 출력
print()



---



## 큐(Queue)

- 선입선출(FIFO:First-In First-Out)의 자료구조
- 가장 먼저 들어온 데이터가 가장 먼저 나감

### @큐의 연산
|연산|설명|
|---|---|
|enqueue(e) |새로운 요소 e를 큐의 맨 뒤에 추가 |
|dequeue() |큐의 맨 앞에 있는 요소를 꺼내서 반환 |
|peek |큐의 맨 위에 있는 요소를 삭제하지 않고 반환  |
|isEmpty() |큐가 비어 있는지 확인, True/False 반환 |
|isFull() |큐가 가득 차 있는지 확인, True/False 반환 |
|size() |큐에 들어 있는 전체 요소의 수 반환 |


### [실습] 배열로 원형 큐 클래스 구현하기
- 용량이 고정된 원형 큐 클래스

- 1.큐 클래스(ArrayQueue) 생성하기

In [ ]:
# 1.(원형 큐) : 클래스 정의 와 생성자
class ArrayQueue:
    def __init__(self, capacity=10):
        self.capacity = capacity
        self.array = [None] * capacity
        self.front = 0
        self.rear = 0

    # 2.(원형 큐) : 공백 상태와 포화 상태 검사
    def isEmpty(self):



    def isFull(self):



    # 3.(원형 큐) : 삽입 연산
    def enqueue(self, item):




    # 4.(원형 큐) : 삭제 연산
    def dequeue(self):



    # 5. (원형 큐) : 상단 참조 연산
    def peek(self):



    # 6. (원형 큐) : 전체 요소 수
    def size(self):



    # 7. (원형 큐) : 전체 요소 화면에 출력
    def display(self, msg='Queue: '):
        print(msg, end='=[')
        count = self.size()
        for i in range(count):
            print(self.array[(self.front+1+i)%self.capacity], end=' ')
        print("]")

- 2.큐 테스트 프로그램 실행하기

In [ ]:
import random
q = ArrayQueue(8)                    # 큐 객체를 생성(capacity=8)

q.display("초기 상태")
while not q.isFull() :               # 큐에 빈 칸인 남았으면
    q.enqueue(random.randint(0,100)) # 0~99사이의 정수 발생->삽입
q.display("포화 상태")

print("삭제 순서: ", end='')
while not q.isEmpty() :             # 큐에 요소가 남아 있으면
    print(q.dequeue(), end=' ')     # 꺼내서 화면에 출력
print()

### [실습] 원형 큐를 링 버퍼로 구현하기

- 1.링 버퍼 적용한 클래스

In [ ]:
# 1.(원형 큐) : 클래스 정의 와 생성자
class ArrayQueue:
    def __init__(self, capacity=10):
        self.capacity = capacity
        self.array = [None] * capacity
        self.front = 0
        self.rear = 0

    # 2.(원형 큐) : 공백 상태와 포화 상태 검사
    def isEmpty(self):
        return self.front == self.rear

    def isFull(self):
        return self.front == (self.rear+1)%self.capacity

    # 3.(원형 큐) : 삽입 연산
    def enqueue(self, item):
        if not self.isFull():
            self.rear = (self.rear+1)%self.capacity # 후단 회전
            self.array[self.rear] = item
        else:
            print('stack overflow!')
            pass

    # 4.(원형 큐) : 삭제 연산
    def dequeue(self):
        if not self.isEmpty():
            self.front = (self.front+1)%self.capacity  # 전단 회전
            return self.array[self.front]

    # 5. (원형 큐) : 상단 참조 연산
    def peek(self):
        if not self.isEmpty():
            return self.array[(self.front+1)%self.capacity]
        else: pass

    # 6. (원형 큐) : 전체 요소 수
    def size(self):
        return (self.rear - self.front + self.capacity) % self.capacity

    # 7. (원형 큐) : 전체 요소 화면에 출력
    def display(self, msg='Queue: '):
        print(msg, end=' = [')
        count = self.size()
        for i in range(count):
            print(self.array[(self.front+1+i)%self.capacity], end=' ')
        print("]")

    # 8. (원형 큐) : 링 버퍼를 위한 삽입 연산
    def enqueue2(self, item):             # 링 버퍼 삽입 연산





- 2. 링 버퍼 테스트 프로그램

In [ ]:
import random
q = ArrayQueue(8)               # 큐 객체를 생성(capacity=8)

q.display("초기 상태")
for i in range(6) :             # enqueue2(): 0, 1, 2, 3, 4, 5
    q.enqueue2(i)
q.display("삽입 0-5")

q.enqueue2(6); q.enqueue2(7)    # enqueue2(): 6, 7
q.display("삽입 6,7")           # 포화 발생

q.enqueue2(8); q.enqueue2(9)    # enqueue2(): 8, 9
q.display("삽입 8,9")

q.dequeue(); q.dequeue()        # dequeue() 2회
q.display("삭제  x2")

### @덱(Deque)

- 덱(deque) : double-ended queue
- 전단과 후단에서 모두 삽입과 삭제가 가능한 큐

### [실습] 원형 큐 상속을 이용한 덱 구현하기

- 1. 덱 클래스 생성

In [ ]:
# 원형 큐 클래스 상속받아 원형 덱 클래스 생성
class CircularDeque(ArrayQueue) :
    def __init__( self, capacity=10 ) :
        super().__init__(capacity)

    # 원형 덱: 동작이 동일한 연산들
    def addRear( self, item ): self.enqueue(item )
    def deleteFront( self ): return self.dequeue()
    def getFront( self ): return self.peek()

    # 원형 덱: 추가된 연산들
    def addFront( self, item ):
        if not self.isFull():
            self.array[self.front] = item
            self.front = (self.front - 1 + self.capacity) % self.capacity # 전단 회전
        else: pass

    def deleteRear( self ):
        if not self.isEmpty():
            item = self.array[self.rear];
            self.rear = (self.rear - 1 + self.capacity) % self.capacity  # 후단 회전
            return item
        else: pass

    def getRear( self ):
        if not self.isEmpty():
            return self.array[self.rear]
        else: pass

- 2. 덱 테스트 프로그램

In [ ]:
dq = CircularDeque()

for i in range(9):
    if i%2==0 : dq.addRear(i)
    else : dq.addFront(i)
dq.display("홀수는 전단, 짝수는 후단 삽입")

for i in range(2): dq.deleteFront()
for i in range(3): dq.deleteRear()
dq.display("전단 삭제 2번, 후단 삭제 3번")

for i in range(9,14): dq.addFront(i)
dq.display("전단에 9 ~ 13 삽입")

### @파이썬에서 큐와 덱 사용하기

#### 방법 1) queue 모듈의 Queue 사용하기

In [ ]:
import random                   # 난수 발생을 위해 random 모듈 포함
import queue                    # 파이썬의 큐 모듈 포함
q = queue.Queue(8)              # 큐 객체를 생성(capacity=8)

print("삽입 순서: ", end='')
while not q.full() :            # 큐에 빈 칸인 남았으면
    v = random.randint(0,100)   # 0~99사이의 정수 발생
    q.put(v)                    # 삽입
    print(v, end=' ')
print()

print("삭제 순서: ", end='')
while not q.empty() :         # 큐에 요소가 남아 있으면
    print(q.get(), end=' ')   # 꺼내서 화면에 출력
print()

#### 방법 2) collections모듈의 deque 클래스 사용하기

In [ ]:
import collections              # 덱을 사용하기 위해 collections 모듈 포함
dq = collections.deque()        # 덱 객체를 생성

print("덱은 공백상태 아님" if dq else "덱은 공백상태")
for i in range(9):
    if i%2==0 : dq.append(i)
    else : dq.appendleft(i)
print("홀수는 전단, 짝수는 후단 삽입", dq)

for i in range(2): dq.popleft()
for i in range(3): dq.pop()
print("전단 삭제 2번, 후단 삭제 3번", dq)

for i in range(9,14): dq.appendleft(i)
print("전단에 9 ~ 13 삽입          ", dq)

print("덱은 공백상태 아님" if dq else "덱은 공백상태")



---



## 리스트(List)



---

