In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix
import seaborn as sns

In [3]:
file_path = r"C:\Users\MinGi\Desktop\year3-sem1\인공지능개론\dataset\car_evaluation.csv"
df = pd.read_csv(file_path)

print(df.head())
print(df.isnull().sum())

   vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc
vhigh      0
vhigh.1    0
2          0
2.1        0
small      0
low        0
unacc      0
dtype: int64


In [4]:
label_encoder = {}
for column in df.columns:
    label_encoder[column] = LabelEncoder()
    df[column] = label_encoder[column].fit_transform(df[column])
    print("\n", df[column].value_counts())


 vhigh
0    432
2    432
1    432
3    431
Name: count, dtype: int64

 vhigh.1
0    432
2    432
1    432
3    431
Name: count, dtype: int64

 2
1    432
2    432
3    432
0    431
Name: count, dtype: int64

 2.1
1    576
2    576
0    575
Name: count, dtype: int64

 small
1    576
0    576
2    575
Name: count, dtype: int64

 low
2    576
0    576
1    575
Name: count, dtype: int64

 unacc
2    1209
0     384
1      69
3      65
Name: count, dtype: int64


In [9]:
x = df.drop('unacc', axis=1)
y = df['unacc']

scaler = StandardScaler()
x = scaler.fit_transform(x)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0, stratify=y)

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(1208, 6) (1208,)
(519, 6) (519,)


In [10]:
# DT
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=0)
dt_model.fit(x_train, y_train)
y_pred_dt = dt_model.predict(x_test)

print("DT Accuracy:", accuracy_score(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_dt))

DT Accuracy: 0.9691714836223507
[[111   1   2   1]
 [  2  18   0   1]
 [  6   0 357   0]
 [  1   2   0  17]]


In [11]:
# RF
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(random_state=0)
rf_model.fit(x_train, y_train)
y_pred_rf = rf_model.predict(x_test)

print("RF Accuracy:", accuracy_score(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))

RF Accuracy: 0.9556840077071291
[[110   0   5   0]
 [  4  17   0   0]
 [ 11   0 352   0]
 [  2   1   0  17]]


In [12]:
# SVM
from sklearn.svm import SVC

svm_model = SVC(random_state=0)
svm_model.fit(x_train, y_train)
y_pred_svm = svm_model.predict(x_test)

print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print(confusion_matrix(y_test, y_pred_svm))

SVM Accuracy: 0.8689788053949904
[[ 93   0  22   0]
 [ 21   0   0   0]
 [ 21   0 342   0]
 [  4   0   0  16]]


In [13]:
# LR
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(random_state=0)
lr_model.fit(x_train, y_train)
y_pred_lr = lr_model.predict(x_test)

print("Accuracy LR:", accuracy_score(y_test, y_pred_lr))
print(confusion_matrix(y_test, y_pred_lr))

Accuracy LR: 0.697495183044316
[[ 18   0  91   6]
 [  5   0  16   0]
 [ 21   0 342   0]
 [  8   0  10   2]]


In [18]:
# KNN
from sklearn.neighbors import KNeighborsClassifier

k_range = range(1, 101)
scores = []

for k in k_range:
    knn_model = KNeighborsClassifier(n_neighbors=k)
    knn_model.fit(x_train, y_train)
    y_pred_knn = knn_model.predict(x_test)
    scores.append(accuracy_score(y_test, y_pred_knn))
max_index = max(scores)
optimal_k = scores.index(max_index)

knn_model = KNeighborsClassifier(n_neighbors=optimal_k)
knn_model.fit(x_train, y_train)
y_pred_knn = knn_model.predict(x_test)

print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))
print(confusion_matrix(y_test, y_pred_knn))

KNN Accuracy: 0.8978805394990366
[[100   0  15   0]
 [ 16   5   0   0]
 [ 15   0 348   0]
 [  7   0   0  13]]
